import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, RefreshCw, Route as RouteIcon, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../../services/api";

type Alt = {
  id:number; disruption_id?:number; alternative_code?:string; action_type?:string; title?:string; description?:string;
  predicted_delay_minutes?:number|string|null; predicted_cost?:number|string|null; conflict_count?:number|null;
  feasibility_score?:number|string|null; ml_rank_score?:number|string|null; is_feasible?:boolean; status?:string;
};

function read(data:unknown):Alt[]{if(Array.isArray(data))return data as Alt[];if(!data||typeof data!=="object")return[];const o=data as Record<string,unknown>;return Array.isArray(o.alternatives)?o.alternatives as Alt[]:[]}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function pct(v:unknown){const x=n(v);return Math.round(x<=1?x*100:x)}

export default function OperatorAlternatives(){
  const navigate=useNavigate();
  const [items,setItems]=useState<Alt[]>([]);
  const [busy,setBusy]=useState<number|null>(null);
  const [message,setMessage]=useState("");

  const load=useCallback(async()=>{const r=await api.get("/operator/alternatives");setItems(read(r.data).sort((a,b)=>n(b.ml_rank_score)-n(a.ml_rank_score)))},[]);
  useEffect(()=>{void load();},[load]);

  async function choose(item:Alt){
    if(item.is_feasible===false)return;
    setBusy(item.id);setMessage("");
    try{await api.post(`/operator/alternatives/${item.id}/select`,{note:"Selected from Operator Alternatives page."});setMessage("Operational alternative selected.");await load();}
    finally{setBusy(null);}
  }

  return <main style={{minHeight:"100vh",background:"#f3eee4",color:"#18384a"}}>
    <header style={{minHeight:72,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 26px",background:"#0e2d43",color:"#fff",borderBottom:"3px solid #d4662b"}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}>
        <button onClick={()=>navigate("/operator")} style={{width:38,height:38,border:"1px solid rgba(255,255,255,.18)",borderRadius:8,background:"rgba(255,255,255,.06)",color:"#fff",cursor:"pointer"}}><ArrowLeft size={18}/></button>
        <div><strong style={{fontFamily:"Georgia,serif",fontSize:25}}>Operational Alternatives</strong><div style={{color:"#b9cbd5",fontSize:9,fontWeight:900,letterSpacing:".15em"}}>AI / RULE RANKED ACTIONS</div></div>
      </div>
      <button onClick={()=>void load()} style={{height:38,display:"flex",alignItems:"center",gap:6,padding:"0 11px",border:0,borderRadius:6,background:"rgba(255,255,255,.08)",color:"#fff",cursor:"pointer"}}><RefreshCw size={14}/>Refresh</button>
    </header>

    <section style={{maxWidth:1200,margin:"0 auto",padding:22}}>
      {message&&<div style={{padding:10,background:"#edf6ef",color:"#316b46",borderRadius:7,marginBottom:12}}>{message}</div>}
      <h1 style={{fontFamily:"Georgia,serif",fontSize:29,marginBottom:5}}>Ranked Control Actions</h1>
      <p style={{marginTop:0,color:"#6b7d86",fontSize:11}}>Only feasible alternatives generated by the backend can be selected. Train Control retains final authority.</p>

      <div style={{display:"grid",gap:10,marginTop:14}}>
        {items.map((item,index)=>{
          const selected=String(item.status??"").toUpperCase()==="SELECTED";
          const feasible=item.is_feasible!==false;
          return <article key={item.id} style={{padding:14,border:"1px solid #ddd0bf",borderRadius:9,background:selected?"#edf5ef":"#fffdf9"}}>
            <div style={{display:"flex",justifyContent:"space-between",gap:12}}>
              <div><span style={{color:"#9a5c1e",fontSize:8,fontWeight:900}}>RANK #{index+1} · {item.alternative_code}</span><h3 style={{margin:"4px 0 5px"}}>{item.title ?? item.action_type}</h3><p style={{margin:0,color:"#6e7e86",fontSize:10}}>{item.description}</p></div>
              <div style={{textAlign:"right"}}><strong style={{fontSize:25}}>{pct(item.ml_rank_score)}%</strong><small style={{display:"block",color:"#71818a"}}>RANK SCORE</small></div>
            </div>
            <div style={{display:"flex",gap:12,marginTop:10,fontSize:9,color:"#5d7079"}}><span>Delay {Math.round(n(item.predicted_delay_minutes))}m</span><span>Conflicts {item.conflict_count??0}</span><span>Feasibility {pct(item.feasibility_score)}%</span></div>
            <button disabled={!feasible||selected||busy===item.id} onClick={()=>void choose(item)} style={{marginTop:10,minHeight:36,padding:"0 14px",border:0,borderRadius:6,background:selected?"#39704a":feasible?"#174a65":"#c7cbcb",color:"#fff",fontWeight:900,cursor:feasible&&!selected?"pointer":"default"}}>
              {selected?<><CheckCircle2 size={14} style={{verticalAlign:"middle",marginRight:5}}/>SELECTED</>:feasible?<><RouteIcon size={14} style={{verticalAlign:"middle",marginRight:5}}/>SELECT ACTION</>:<><ShieldCheck size={14} style={{verticalAlign:"middle",marginRight:5}}/>INFEASIBLE</>}
            </button>
          </article>
        })}
      </div>
    </section>
  </main>
}
