"""create core railsync tables

Revision ID: 5050ac158dad
Revises: 
Create Date: 2026-09-06 10:58:08.240300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5050ac158dad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(length=20), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('station_type', sa.Enum('STATION', 'JUNCTION', 'HALT', 'TERMINAL', 'YARD', 'OTHER', name='station_type'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('operational_status', sa.Enum('OPEN', 'RESTRICTED', 'MAINTENANCE', 'PARTIAL_BLOCK', 'BLOCKED', 'TEMP_CLOSED', 'EMERGENCY_CLOSED', name='station_operational_status'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_stations_id'), 'railway_stations', ['id'], unique=False)
    op.create_index(op.f('ix_railway_stations_operational_status'), 'railway_stations', ['operational_status'], unique=False)
    op.create_index(op.f('ix_railway_stations_station_code'), 'railway_stations', ['station_code'], unique=True)
    op.create_index(op.f('ix_railway_stations_station_name'), 'railway_stations', ['station_name'], unique=False)
    op.create_index(op.f('ix_railway_stations_station_type'), 'railway_stations', ['station_type'], unique=False)
    op.create_table('railway_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('line_name', sa.String(length=255), nullable=True),
    sa.Column('railway_type', sa.String(length=100), nullable=True),
    sa.Column('gauge', sa.String(length=50), nullable=True),
    sa.Column('electrified', sa.Boolean(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('operational_status', sa.Enum('OPEN', 'RESTRICTED', 'MAINTENANCE', 'PARTIAL_BLOCK', 'BLOCKED', 'TEMP_CLOSED', 'EMERGENCY_CLOSED', name='track_operational_status'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_tracks_id'), 'railway_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_railway_tracks_line_name'), 'railway_tracks', ['line_name'], unique=False)
    op.create_index(op.f('ix_railway_tracks_operational_status'), 'railway_tracks', ['operational_status'], unique=False)
    op.create_index(op.f('ix_railway_tracks_osm_id'), 'railway_tracks', ['osm_id'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('train_name', sa.String(length=255), nullable=False),
    sa.Column('train_type', sa.String(length=100), nullable=True),
    sa.Column('source_station_code', sa.String(length=20), nullable=True),
    sa.Column('destination_station_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_destination_station_code'), 'trains', ['destination_station_code'], unique=False)
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_source_station_code'), 'trains', ['source_station_code'], unique=False)
    op.create_index(op.f('ix_trains_train_name'), 'trains', ['train_name'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'MANAGER', 'TRAIN_OPERATOR', name='user_role'), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('station_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'MAINTENANCE', 'PARTIAL_BLOCK', 'BLOCKED', 'TEMP_CLOSED', 'EMERGENCY_CLOSED', name='station_status_event_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['railway_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_status_events_id'), 'station_status_events', ['id'], unique=False)
    op.create_index(op.f('ix_station_status_events_is_active'), 'station_status_events', ['is_active'], unique=False)
    op.create_index(op.f('ix_station_status_events_station_id'), 'station_status_events', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_status_events_status'), 'station_status_events', ['status'], unique=False)
    op.create_table('track_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'MAINTENANCE', 'PARTIAL_BLOCK', 'BLOCKED', 'TEMP_CLOSED', 'EMERGENCY_CLOSED', name='track_status_event_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['railway_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_status_events_id'), 'track_status_events', ['id'], unique=False)
    op.create_index(op.f('ix_track_status_events_is_active'), 'track_status_events', ['is_active'], unique=False)
    op.create_index(op.f('ix_track_status_events_status'), 'track_status_events', ['status'], unique=False)
    op.create_index(op.f('ix_track_status_events_track_id'), 'track_status_events', ['track_id'], unique=False)
    op.create_table('train_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('speed_kmph', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('current_station_code', sa.String(length=20), nullable=True),
    sa.Column('next_station_code', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_positions_id'), 'train_positions', ['id'], unique=False)
    op.create_index(op.f('ix_train_positions_recorded_at'), 'train_positions', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_train_positions_train_id'), 'train_positions', ['train_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_positions_train_id'), table_name='train_positions')
    op.drop_index(op.f('ix_train_positions_recorded_at'), table_name='train_positions')
    op.drop_index(op.f('ix_train_positions_id'), table_name='train_positions')
    op.drop_table('train_positions')
    op.drop_index(op.f('ix_track_status_events_track_id'), table_name='track_status_events')
    op.drop_index(op.f('ix_track_status_events_status'), table_name='track_status_events')
    op.drop_index(op.f('ix_track_status_events_is_active'), table_name='track_status_events')
    op.drop_index(op.f('ix_track_status_events_id'), table_name='track_status_events')
    op.drop_table('track_status_events')
    op.drop_index(op.f('ix_station_status_events_status'), table_name='station_status_events')
    op.drop_index(op.f('ix_station_status_events_station_id'), table_name='station_status_events')
    op.drop_index(op.f('ix_station_status_events_is_active'), table_name='station_status_events')
    op.drop_index(op.f('ix_station_status_events_id'), table_name='station_status_events')
    op.drop_table('station_status_events')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_train_name'), table_name='trains')
    op.drop_index(op.f('ix_trains_source_station_code'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_index(op.f('ix_trains_destination_station_code'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_railway_tracks_osm_id'), table_name='railway_tracks')
    op.drop_index(op.f('ix_railway_tracks_operational_status'), table_name='railway_tracks')
    op.drop_index(op.f('ix_railway_tracks_line_name'), table_name='railway_tracks')
    op.drop_index(op.f('ix_railway_tracks_id'), table_name='railway_tracks')
    op.drop_table('railway_tracks')
    op.drop_index(op.f('ix_railway_stations_station_type'), table_name='railway_stations')
    op.drop_index(op.f('ix_railway_stations_station_name'), table_name='railway_stations')
    op.drop_index(op.f('ix_railway_stations_station_code'), table_name='railway_stations')
    op.drop_index(op.f('ix_railway_stations_operational_status'), table_name='railway_stations')
    op.drop_index(op.f('ix_railway_stations_id'), table_name='railway_stations')
    op.drop_table('railway_stations')
    # ### end Alembic commands ###

